<?php

require_once(__DIR__.'/../../Controller/IndexController.php');

$autor = $_POST['autor'];
$titulo = $_POST['titulo'];
$noticia = $_POST['noticia'];
$tags = $_POST['tags'];
$id = $_POST['id'];

$cnt = new IndexController();
$cnt->editContenido($id, $autor, $titulo, $noticia, $tags);

?><html>
	<head>
		<style type="text/css">
				.wrapper {
  position: relative;
  z-index: 1;
  background: #FFFFFF;
  max-width: 360px;
  margin: 0 auto 100px;
  padding: 45px;
  text-align: center;
  box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
  background: #fff;
  border-radius: 10px;
  overflow: hidden;
  margin-top: 200px;
}

body{
	background-image: url("https://i.blogs.es/b9b1ca/musica/1366_2000.jpg");
  background-repeat: no-repeat; 
  background-size: 100%
}

.botonedit {
	-moz-box-shadow:inset 0px 39px 0px -24px #e67a73;
	-webkit-box-shadow:inset 0px 39px 0px -24px #e67a73;
	box-shadow:inset 0px 39px 0px -24px #e67a73;
	background-color:#e4685d;
	-moz-border-radius:4px;
	-webkit-border-radius:4px;
	border-radius:4px;
	border:1px solid #ffffff;
	display:inline-block;
	cursor:pointer;
	color:#ffffff;
	font-family:Arial;
	font-size:15px;
	padding:6px 15px;
	text-decoration:none;
	text-shadow:0px 1px 0px #b23e35;
}
.botonedit:hover {
	background-color:#eb675e;
}
.botonedit:active {
	position:relative;
	top:1px;
}

h1{
	font-family: verdana;
	color:green;
	font-style: bold;
}

a{
	font-family:Times-New-Roman;
	font-style: normal;
	color:black;
	font-size:30px;
	
}
		</style>
		<title>Editado</title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	</head>
	<body>
		<div class="wrapper">
			<h1>Contenido editado correctamente</h1><a>Que quieres hacer ahora?<br></a><br>
			<a class="botonedit" href="../Forms/formContenido.phtml">Agregar una documentación</a>
			<br><br>
			<a class="botonedit" href="../Index.phtml">Ir a la pagina incial</a>
		</div>
	</body>
</html>