<?php 
    require_once(__DIR__.'/../../Controller/IndexController.php');


?><html>
	<head>
		<style type="text/css">
				body {
  margin: 0 auto;
  width: 600px;
  font-family: 'Dosis';
  background-image: url("https://i.pinimg.com/originals/f8/07/d4/f807d4d14ce3acc9a3db5ea98ce723ff.jpg");
  background-repeat: no-repeat; 
  background-size: 120%;
  
}

a{
  cursor:pointer;
}


a.palette-item {
  height: 1em;
  border-radius: 3px;
  margin: 2px 1px;
  width: 1em;
}

h1{
color:white;
}
		
h2{
color:white;
}

label{
color:white;
font:bold;
}
		
#button{
cursor:pointer;
display:inline-block;
padding:0.3em 1.2em;
margin:0 0.3em 0.3em 0;
border-radius:2em;
box-sizing: border-box;
text-decoration:none;
font-family:'Roboto',sans-serif;
font-weight:300;
color:#FFFFFF;
background-color:#4eb5f1;
text-align:center;
transition: all 0.2s;
}
#button:hover{
background-color:#AC8ADA;
}

.button:active {
	position:relative;
	top:1px;
}

.button2 {
	background-color:#44c767;
	-moz-border-radius:28px;
	-webkit-border-radius:28px;
	border-radius:28px;
	border:1px solid #18ab29;
	display:inline-block;
	cursor:pointer;
	color:#ffffff;
	font-family:Arial;
	font-size:17px;
	padding:16px 31px;
	text-decoration:none;
	text-shadow:0px 1px 0px #2f6627;
}
.button2:hover {
	background-color:#5cbf2a;
}
.button2:active {
	position:relative;
	top:1px;
}

#formid,#formautor,#formtitulo,#formCont {
border-radius:5%;
margin:2.1%;
width: 45%;
height:4%;
}

		</style>
		
		</style>
	</head>
	<body>
		<div id="wrapper">
		    <h1>Proyecto final</h1>
		    <h2>Añadir contenido</h2>
			<div id="formConten">
				<form action="addContenido.phtml" method="post">
					<dl>
						<dt><label for="formpri">Autor</label></dt>
						<dd><input type="text" id="formnom" name="autor"/></dd>
						<dt><label for="formCont">Titulo</label></dt>
						<dd><input type="text" id="formtitulo" name="titulo"/></dd>
						<dt><label for="formCont">Contenido</label></dt>
						<dd><textarea id="formConte" name="noticia" cols="80" rows="10"></textarea></dd>
						<dt><label for="formCont">Tags</label></dt>
						<dd><input type="text" id="formCont" name="tags"/></dd><br>
						<dd><input type="submit" value="Crear Contenido" id="botonadd"/></dd>
					</dl>
				</form>
			</div>
			<a class="button2" href="../Index.phtml">Volver al inicio</a>
		<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
		</div>
	</body>
</html>