<?php 

require_once(__DIR__.'/../../Controller/UserController.php');


?><html>
	<head>
		<style type="text/css">
			.login-page {
  width: 360px;
  padding: 8% 0 0;
  margin: auto;
}
.form {
  position: relative;
  z-index: 1;
  background: #FFFFFF;
  max-width: 360px;
  margin: 0 auto 100px;
  padding: 45px;
  text-align: center;
  box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
  background: #fff;
  border-radius: 10px;
  overflow: hidden;
  margin-top: 100px;
}
.form input {
  font-family: "Roboto", sans-serif;
  outline: 0;
  background: #f2f2f2;
  width: 100%;
  border: 0;
  margin: 0 0 15px;
  padding: 15px;
  box-sizing: border-box;
  font-size: 14px;
  
}
.button {
  font-family: "Roboto", sans-serif;
  text-transform: uppercase;
  outline: 0;
  background: #9898f2;
  width: 100%;
  border: 0;
  padding: 15px;
  color: #9898f2;
  font-size: 14px;
  -webkit-transition: all 0.3 ease;
  transition: all 0.3 ease;
  cursor: pointer;
}
.button:hover, .button:active, .button:focus {
  background: #9b7171;
}

.container {
  position: relative;
  z-index: 1;
  max-width: 300px;
  margin: 0 auto;
}

body {
  background: #5EBDAD; 
  background: -webkit-linear-gradient(right, #5EBDAD, #D4EC3B);
  background: -moz-linear-gradient(right, #5EBDAD, #D4EC3B);
  background: -o-linear-gradient(right, #5EBDAD, #D4EC3B);
  background: linear-gradient(to left, #5EBDAD, #D4EC3B);
  font-family: "Roboto", sans-serif;
}

.login100-form-title {
  display: block;
  font-family: Arial-Narrow;
  font-size: 50px;
  color: #555555;
  line-height: 1.2;
  text-align: center;
}

.txt1 {
  font-family: OpenSans-Regular;
  font-size: 15px;
  line-height: 1.4;
  color: #999999;
}

.txt2 {
  font-family: OpenSans-Regular;
  font-size: 15px;
  line-height: 1.4;
  color: #4272d7;
}

.hov1:hover {
  text-decoration: underline;
}
		</style>
		<title>Login User</title>
		<meta charset="UTF-8">
	</head>
	<body style="background-color:#83BF1A;">
		<div id="wrapper">
		 
			<div id="formUser">
				<form action="loginUser.phtml" method="post">
								<div class="form">
								  <span class="login100-form-title p-b-33">
						 Login
					</span>
						<form class="login-form">
						<input type="text" id="formusername" name="UserName" placeholder="Usuario"/>
						<input type="password" id="formpassword" name="Password" placeholder="Password"/>
						<input type="submit" value="Entrar" class ="button" />
						</form>
						<br>
						<div class="text-center">
						<span class="txt1">
							Aun no tienes creada una cuenta?
						</span>
						<a href="FormRegister.phtml" class="txt2 hov1">
							Sign up
						</a>
					</div>
				</form>
				</div>
				</form>
			</div>
		</div>
	</body>
</html>