<?php
require_once(__DIR__.'/../../Controller/UserController.php');

session_start();

$UserName = $_POST['UserName'];
$Password = $_POST['Password'];

$cnt = new UserController();
$login = $cnt->loginUser($UserName, $Password);

?>
<html>
	<head>
	    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
		<title>Login</title>
		<style type="text/css">
		    
.cuadrado {
  position: relative;
  z-index: 1;
  background: #FFFFFF;
  max-width: 360px;
  margin: 0 auto 100px;
  padding: 45px;
  text-align: center;
  box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
  background: #fff;
  border-radius: 10px;
  overflow: hidden;
  margin-top: 100px;
}

body {
   background-image: url("https://img.freepik.com/foto-gratis/blur-naturaleza-parque-verde-bokeh-luz-sol-resumen-antecedentes-copie-espacio-aventura-viaje-concepto-medio-ambiente-estilo-color-filtro-tono-vendimia_1253-1107.jpg?size=626&ext=jpg");
  background-repeat: no-repeat; 
  background-size: 100%
}

.button1 {
	background-color:#44c767;
	-moz-border-radius:28px;
	-webkit-border-radius:28px;
	border-radius:28px;
	border:1px solid #18ab29;
	display:inline-block;
	cursor:pointer;
	color:#ffffff;
	font-family:Arial;
	font-size:17px;
	padding:16px 31px;
	text-decoration:none;
	text-shadow:0px 1px 0px #2f6627;
}
.button1:hover {
	background-color:#5cbf2a;
}
.button1:active {
	position:relative;
	top:1px;
}
h1{
    color:red;
    font-style: normal;
    font-family: helvetica;
    font-size: 14px
}
		</style>
	</head>
	<body>
		<div id="wrapper">

<?php
    if($login)
    {
        echo '<div class= "cuadrado">';
        echo'<h1>Bienvenido!</h1>';
        $_SESSION["UserName"] = $UserName;
        echo "Usuario: " . $UserName;
        echo '<br>';
        echo '<br>';
        echo '<a href="../Index.phtml" class="button1">Ir a la pagina inicial</a>';
        echo '</div>';
        
    }
    else
    {
         echo '<div class= "cuadrado">';
        echo'<h1>Ups! Datos introducidos no correctos<br> Revisa tu contraseña o usuario</h1>';
        echo'<a href="../Forms/FormLogin.phtml" class="button1">Vuelve a intentarlo</a>';
        echo '</div>';
    }
?>
		
		</div>
	</body>
</html>