version: '3.8'
services:
  mysql:
    image: mysql:5.6
    container_name: docker-mysql
    environment:
      MYSQL_DATABASE: project
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "33060:33060"
    restart: always
  web:
    build: './php/'
    container_name: docker-php
    ports:
      - "8000:80"
    volumes:
      - ./www:/var/www/html
    links:
     - mysql
